### ISSUE TITLE
firepython.middleware.FirePythonWSGI breaks on Django 1.2 alpha 1

### ISSUE THREAD

**Issue by xarg** [binaryage/firelogger.py#9]
Here is my config: 
Django version: 1.2 alpha 1 - latest trunk
MIDDLEWARE_CLASSES: firepython.middleware.FirePythonWSGI
Server: Apache 2 on Ubuntu with mod_wsgi

django.wsgi:

<pre>
import os
import sys

sys.path.append(os.path.abspath(os.path.dirname(__file__)))
os.environ['DJANGO_SETTINGS_MODULE'] = 'settings'

import django.core.handlers.wsgi
application = django.core.handlers.wsgi.WSGIHandler()
</pre>

Traceback:

<pre>
[Mon Jan 25 23:39:16 2010] [error] [client 192.168.1.2] mod_wsgi (pid=12287): Exception occurred processing WSGI script '/home/sasha/Projects/django/django.wsgi'.
[Mon Jan 25 23:39:16 2010] [error] [client 192.168.1.2] Traceback (most recent call last):
[Mon Jan 25 23:39:16 2010] [error] [client 192.168.1.2] Traceback (most recent call last):
[Mon Jan 25 23:39:16 2010] [error] [client 192.168.1.2]   File "/usr/local/lib/python2.6/dist-packages/django/core/handlers/wsgi.py", line 230, in __call__
[Mon Jan 25 23:39:16 2010] [error] [client 192.168.1.2]   File "/usr/local/lib/python2.6/dist-packages/django/core/handlers/wsgi.py", line 230, in __call__
[Mon Jan 25 23:39:16 2010] [error] [client 192.168.1.2]     self.load_middleware()
[Mon Jan 25 23:39:16 2010] [error] [client 192.168.1.2]   File "/usr/local/lib/python2.6/dist-packages/django/core/handlers/base.py", line 49, in load_middleware
[Mon Jan 25 23:39:16 2010] [error] [client 192.168.1.2]     mw_instance = mw_class()
[Mon Jan 25 23:39:16 2010] [error] [client 192.168.1.2] TypeError: __init__() takes at least 2 arguments (1 given)
</pre>

**Comment by darwin** [comment]
I'm sorry I'm unable to help here. I don't use Django ...

**Comment by reduxionist** [comment]
I've just successfully added FirePython to a Django deployment, and suspect the problem here may have been in the .wsgi definition file. For others considering using this with Django, do not be disheartened - it was easy to setup and is alread proving to be of great value! Thanks very very much Darwin!
